### ISSUE TITLE
ENOMEM error.

### ISSUE THREAD

**Issue by face-hh** [coder/deploy-code-server#55]
Server was running slower since i opened it, and saw yesterday that my specs (server) says:
![image](https://user-images.githubusercontent.com/69168154/129597711-95f9e46f-729f-46a8-b475-ef37c70bbf93.png)
 
I'm asking myself how can some files have 230GB so far in size...

I also get errors such as:
![image](https://user-images.githubusercontent.com/69168154/129598553-73d9e713-8aee-4294-bbed-121da7dfcbc8.png)

This cause a lot of errors, such as ENOTEMPTY.
I googled that "killed error" and it resulted to ENOMEM, warn i get on downloading any package.

![image](https://user-images.githubusercontent.com/69168154/129598681-e5e5a722-4353-42ad-906f-104395abb7a6.png)

**Comment by face-hh** [comment]
Now i face with this issue, no memory related
![image](https://user-images.githubusercontent.com/69168154/129717423-8f43d7da-eb18-43a8-970b-35a9bc0cf5c5.png)

**Comment by bpmct** [comment]
Hi - sorry for the late response. I think this is due to the fact that Railway had some memory limits at first. Are you still experiencing the MongoDB issue?
