### ISSUE TITLE
Opening Ports?

### ISSUE THREAD

**Issue by AyaanZaveri** [coder/deploy-code-server#57]
How would I open ports on Railway? I'm running live-server for my HTML projects, but I can't seem to access certain ports. Services like **ngrok** and **localtunnel** work, but they always seem to stop running after a while. Google Cloud lets you open ports very easily, so is there a similar way to do it for Railway.

**Thanks!**

**Comment by ramonrey** [comment]
I am having the same issue.

**Comment by bpmct** [comment]
You'll want to install ngrok on the image or in the `/home/coder` directory so you can tunnel ports that way :)

**Comment by kanelee1995** [comment]
> You'll want to install ngrok on the image or in the `/home/coder` directory so you can tunnel ports that way :)

How can we do that on an iPad? Thanks
