### ISSUE TITLE
How to access localhost link that running?

### ISSUE THREAD

**Issue by ishowman** [coder/deploy-code-server#61]
I am using code server to run my project, and it's running url is localhost, how can i visit on my browser?

**Comment by bpmct** [comment]
code-server has a built in [web proxy](https://coder.com/docs/code-server/latest/guide#accessing-web-services) for accessing web services. Using a subdomain is the best option if you are using something like create-react-app.

We're also working on an extension to do this. Let me know if you'd like early access when we finish it :)
