### ISSUE TITLE
can't access code-server on AWS

### ISSUE THREAD

**Issue by wernervandergeest** [coder/deploy-code-server#66]
Hi, I'm unable to access my code-server on AWS; opened http port on the VM and in AWS security rule, I'm struggling to troubleshoot this one, the code-server and coder-redirecter are running, can you give me some tips here?

**Comment by letoast** [comment]
Same problem here

**Comment by fdervisi** [comment]
here as well, any solution on this? Sometimes it works, sometimes fails

**Comment by bpmct** [comment]
Hi - sorry for the late response, I have not been active on this project.

Unfortunately, we cannot guarantee reliability with our `--link` service anymore. I have added a note to our VM guide to specify this. For now, we'd recommend using our guide to configure Caddy/LetsEncrypt on code-server: https://coder.com/docs/code-server/latest/guide#using-lets-encrypt-with-caddy
