### ISSUE TITLE
auto reset on heroku

### ISSUE THREAD

**Issue by Munz1211** [coder/deploy-code-server#73]
why every 1 hour get auto reset from heroku??, how to solve it. The data that I coded disappeared instantly. help

**Comment by bpmct** [comment]
Hi @Munz1211. Sorry for the very late response. Heroku has an [ephemeral filesystem](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) which means that any files are reset and you must add tools to the Dockerfile for them to stay in your workspace.

To save your sourcecode, you can follow these instructions to [persist your filesystem with rclone](https://github.com/coder/deploy-code-server/tree/main/deploy-container#-persist-your-filesystem-with-rclone)
