### ISSUE TITLE
"Extension 'actboy168.tasks' not found." with codercom/code-server:4.0.2

### ISSUE THREAD

**Issue by lwd-temp** [coder/deploy-code-server#80]
"actboy168.tasks" won't be automatically installed when rclone is enabled in version 4.0.2 with Dockerfile.

**Comment by lwd-temp** [comment]
Also, actboy168.tasks can't be found in the default marketplace in 4.0.2.

**Comment by lwd-temp** [comment]
https://github.com/coder/code-server/issues/4899

**Comment by johnny12150** [comment]
@lwd-temp Have you solved this? 
I am still facing the same promblem. Even though this extension is installed in `entrypoint.sh`.

https://github.com/coder/deploy-code-server/blob/457f4c8b8f876f90da60d973d06afb68377ffb80/deploy-container/entrypoint.sh#L37

**Comment by lwd-temp** [comment]
> @lwd-temp Have you solved this? I am still facing the same promblem. Even though this extension is installed in `entrypoint.sh`.
> 
> https://github.com/coder/deploy-code-server/blob/457f4c8b8f876f90da60d973d06afb68377ffb80/deploy-container/entrypoint.sh#L37

This won't be easily solved because `code-server --install-extension` will only install extension in the default marketplace. However, it's not in the default marketplace. I suggest contain the extension package in your deployment files and install it from the package locally as a workaround.
