### ISSUE TITLE
add fly.io guide

### ISSUE THREAD

**Issue by iamyuu** [coder/deploy-code-server#93]

**Comment by ghuntley** [comment]
We would take a pull-request on how to use code-server w/flyio.

**Comment by gedw99** [comment]
this would be nice !!

**Comment by thealidev** [comment]
If you or anyone here know how to do it  
Open a pr with it

**Comment by thealidev** [comment]
@iamyuu

**Comment by matifali** [comment]
There are guides for both deploying `code-server` and `Coder` on fly.io.
1. Deploy code-server: https://fly.io/blog/remote-ide-machines
2. Deploy Coder v2: https://coder.com/blog/remote-developer-environments-on-fly-io
